server:
  port: 8086
spring:
  datasource:
    username: root
    password: Kulkarni@123
    url: 'jdbc:mysql://localhost:3306/moviesdb'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Corrected property name from format-sql to format_sql

